#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 Pablo Seminario <pabluk@gmail.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function, unicode_literals

from Screenkey import APP_NAME, APP_DESC, VERSION
import Screenkey.screenkey as sc

import os
import logging
from argparse import ArgumentParser


def main():
    parser = ArgumentParser(description=APP_DESC, version=VERSION)
    parser.add_argument("--no-detach", action="store_true",
                        dest="nodetach", default=False,
                        help=_("do not detach from the parent"))
    parser.add_argument("-d", "--debug", action="store_true",
                        dest="debug", default=False, help=_("show debug information"))
    parser.add_argument("-t", "--timeout", action="store_true",
                        dest="timeout", default=2.5, help="timeout in seconds (2.5 by default)")
    parser.add_argument("-m", "--mods-only", action="store_true",
                        dest="mods_only", default=None,
                        help="Show ony keys with modifiers pressed")
    options = parser.parse_args()

    if options.debug:
        if options.nodetach:
            # Send debug messages to standard output
            logfile = None
        else:
            logfile = os.path.join(os.path.expanduser('~'), '.screenkey.log')
        logging.basicConfig(filename=logfile, level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(APP_NAME)

    s = Screenkey(logger=logger, nodetach=options.nodetach,
                  timeout=options.timeout, mods_only=options.mods_only)
    gtk.main()


if __name__ == "__main__":
    main()
