#!/bin/bash

DIR=`dirname $0`
cd $DIR

if [ -r /dev/input/event0 ]
then
  python -c 'import libscreenkey.screenkey as s;s.Main()' $*
else
  gksu -D Screenkey "python -c 'import libscreenkey.screenkey as s;s.Main()' $*"
fi
